### ISSUE TITLE
opera_tosca_parser.error.ParseError: [NodeTemplate] Missing requirements: host.

### ISSUE THREAD

**Issue by MohammadErfan-Jabbari** [imperial-qore/COSCO#19]
Hi,
I have a problem running the cosco on physical environment. I run it on VLAN mode. I don't have access to azure, AWS or any other famous cloud provider. I have access to 10 VMs with same resources you have been used in Demo video. I have not ran any specific command on my worker VMs, except for copying the public key.
According to your last video on the youtube playlist, we should run some kind of deplyoyment on the VMs, but I couldn't figure out how can I do that with out using the AZ command you used in the video, and I think my error that I have pasted as the subject of this issue happens because of that.
Could any one please help me with how can I deploy worker's applications on my vms without using cloud provider's specific packages?

**Comment by MohammadErfan-Jabbari** [comment]
to expand my question further, This is the error I face when I run the main.py file

```
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    datacenter, workload, scheduler, env, stats = initalizeEnvironment(env, logger)
  File "main.py", line 89, in initalizeEnvironment
    hostlist = datacenter.generateHosts()
  File "/home/erfan/Project/COSCO/framework/datacenter/Datacenter.py", line 50, in generateHosts
    outputHostsData = Parallel(n_jobs=num_cores)(delayed(self.parallelizedFunc)(i) for i in self.hosts)
  File "/home/erfan/Project/myvenv/lib/python3.8/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/erfan/Project/myvenv/lib/python3.8/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/erfan/Project/myvenv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /request (Caused by None)
```
